<?php

/**
 * This is the model base class for the table "truepartialpositives".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Truepartialpositives".
 *
 * Columns in table "truepartialpositives" available as properties of the model,
 * followed by relations of table "truepartialpositives" available as properties of the model.
 *
 * @property integer $tpp_id
 * @property integer $fingerprint_id
 * @property integer $protein_id
 * @property integer $numberofelements
 *
 * @property Fingerprint $fingerprint
 * @property Protein $protein
 */
abstract class BaseTruepartialpositives extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'truepartialpositives';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Truepartialpositives|Truepartialpositives', $n);
	}

	public static function representingColumn() {
		return 'tpp_id';
	}

	public function rules() {
		return array(
			array('fingerprint_id, protein_id, numberofelements', 'numerical', 'integerOnly'=>true),
			array('fingerprint_id, protein_id, numberofelements', 'default', 'setOnEmpty' => true, 'value' => null),
			array('tpp_id, fingerprint_id, protein_id, numberofelements', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fingerprint' => array(self::BELONGS_TO, 'Fingerprint', 'fingerprint_id'),
			'protein' => array(self::BELONGS_TO, 'Protein', 'protein_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'tpp_id' => Yii::t('app', 'Tpp'),
			'fingerprint_id' => null,
			'protein_id' => null,
			'numberofelements' => Yii::t('app', 'Numberofelements'),
			'fingerprint' => null,
			'protein' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('tpp_id', $this->tpp_id);
		$criteria->compare('fingerprint_id', $this->fingerprint_id);
		$criteria->compare('protein_id', $this->protein_id);
		$criteria->compare('numberofelements', $this->numberofelements);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}