<?php

/**
 * This is the model base class for the table "truepositives".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Truepositives".
 *
 * Columns in table "truepositives" available as properties of the model,
 * followed by relations of table "truepositives" available as properties of the model.
 *
 * @property integer $tp_id
 * @property integer $fingerprint_id
 * @property integer $protein_id
 *
 * @property Fingerprint $fingerprint
 * @property Protein $protein
 */
abstract class BaseTruepositives extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'truepositives';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Truepositives|Truepositives', $n);
	}

	public static function representingColumn() {
		return 'tp_id';
	}

	public function rules() {
		return array(
			array('fingerprint_id, protein_id', 'numerical', 'integerOnly'=>true),
			array('fingerprint_id, protein_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('tp_id, fingerprint_id, protein_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fingerprint' => array(self::BELONGS_TO, 'Fingerprint', 'fingerprint_id'),
			'protein' => array(self::BELONGS_TO, 'Protein', 'protein_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'tp_id' => Yii::t('app', 'Tp'),
			'fingerprint_id' => null,
			'protein_id' => null,
			'fingerprint' => null,
			'protein' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('tp_id', $this->tp_id);
		$criteria->compare('fingerprint_id', $this->fingerprint_id);
		$criteria->compare('protein_id', $this->protein_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}