<?php

/**
 * This is the model base class for the table "falsepartialpositives".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Falsepartialpositives".
 *
 * Columns in table "falsepartialpositives" available as properties of the model,
 * followed by relations of table "falsepartialpositives" available as properties of the model.
 *
 * @property integer $id
 * @property integer $fingerprint_id
 * @property string $code
 * @property string $description
 *
 * @property Fingerprint $fingerprint
 */
abstract class BaseFalsepartialpositives extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'falsepartialpositives';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Falsepartialpositives|Falsepartialpositives', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('fingerprint_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>20),
			array('description', 'length', 'max'=>100),
			array('fingerprint_id, code, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, fingerprint_id, code, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fingerprint' => array(self::BELONGS_TO, 'Fingerprint', 'fingerprint_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'fingerprint_id' => null,
			'code' => Yii::t('app', 'Code'),
			'description' => Yii::t('app', 'Description'),
			'fingerprint' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('fingerprint_id', $this->fingerprint_id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}